apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources: 
- ../prod

namePrefix:
  dev-

patches:
- path: ./deployment.yaml
- path: ./service.yaml

secretGenerator:
- name: env
  behavior: merge
  literals:
    - ENVIRONMENT=local