---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongodb
spec:
  members: 3
  type: ReplicaSet
  version: "6.0.5"
  security:
    authentication:
      modes: ["SCRAM-SHA-1"]
  users:
    - name: <your-username> # Change
      db: admin
      passwordSecretRef:
        name: my-user-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
        - name: readWriteAnyDatabase
          db: admin
        - name: clusterAdmin
          db: erp
        - name: userAdminAnyDatabase
          db: erp
        - name: readWriteAnyDatabase
          db: erp
      scramCredentialsSecretName: my-scram
      additionalConnectionStringConfig:
        readPreference: nearest
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
  additionalConnectionStringConfig:
    readPreference: nearest
  statefulSet:
    spec:
     volumeClaimTemplates:
       - metadata:
          name: data-volume
         spec:
          accessModes: [ "ReadWriteOnce" ]
          resources:
            requests:
              storage: 1Gi
            storageClassName: efs-sc
---
# Only Required Once
apiVersion: v1
kind: Secret
metadata:
  name: my-user-password
type: Opaque
stringData:
  password: <your-password> # Change